const translations = {
    "en": {
        "main_title": "System Design Concepts",
        "main_subtitle": "30 Fundamental concepts visualized and animated.",
        "nav_back": "Back to Concepts",
        "nav_prev": "Previous",
        "nav_next": "Next",
        "viz_placeholder": "Visuals Coming Soon",
        "c01_title": "Client-Server Architecture",
        "c02_title": "IP Address",
        "c03_title": "DNS",
        "c04_title": "Proxy / Reverse Proxy",
        "c05_title": "Latency",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "REST API",
        "c09_title": "GraphQL",
        "c10_title": "Databases",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Vertical Scaling",
        "c13_title": "Horizontal Scaling",
        "c14_title": "Load Balancers",
        "c15_title": "Database Indexing",
        "c16_title": "Replication",
        "c17_title": "Sharding",
        "c18_title": "Vertical Partitioning",
        "c19_title": "Caching",
        "c20_title": "Denormalization",
        "c21_title": "CAP Theorem",
        "c22_title": "Blob Storage",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservices",
        "c27_title": "Message Queues",
        "c28_title": "Rate Limiting",
        "c29_title": "API Gateways",
        "c30_title": "Idempotency"
    },
    "es": {
        "main_title": "Conceptos de Dise\u00f1o de Sistemas",
        "main_subtitle": "30 Conceptos fundamentales visualizados y animados.",
        "nav_back": "Volver al Inicio",
        "nav_prev": "Anterior",
        "nav_next": "Siguiente",
        "viz_placeholder": "Visualizaci\u00f3n Pr\u00f3ximamente",
        "c01_title": "Arquitectura Cliente-Servidor",
        "c02_title": "Direcci\u00f3n IP",
        "c03_title": "DNS",
        "c04_title": "Proxy / Proxy Inverso",
        "c05_title": "Latencia",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "REST API",
        "c09_title": "GraphQL",
        "c10_title": "Bases de Datos",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Escalado Vertical",
        "c13_title": "Escalado Horizontal",
        "c14_title": "Balanceadores de Carga",
        "c15_title": "\u00cdndices de Base de Datos",
        "c16_title": "Replicaci\u00f3n",
        "c17_title": "Sharding (Fragmentaci\u00f3n)",
        "c18_title": "Particionamiento Vertical",
        "c19_title": "Cach\u00e9",
        "c20_title": "Desnormalizaci\u00f3n",
        "c21_title": "Teorema CAP",
        "c22_title": "Almacenamiento de Blobs",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservicios",
        "c27_title": "Colas de Mensajes",
        "c28_title": "Rate Limiting (Limitador)",
        "c29_title": "API Gateways",
        "c30_title": "Idempotencia"
    },
    "fr": {
        "main_title": "Concepts de Conception de Syst\u00e8mes",
        "main_subtitle": "30 Concepts fondamentaux visualis\u00e9s et anim\u00e9s.",
        "nav_back": "Retour \u00e0 l'accueil",
        "nav_prev": "Pr\u00e9c\u00e9dent",
        "nav_next": "Suivant",
        "viz_placeholder": "Bient\u00f4t Disponible",
        "c01_title": "Architecture Client-Serveur",
        "c02_title": "Adresse IP",
        "c03_title": "DNS",
        "c04_title": "Proxy / Reverse Proxy",
        "c05_title": "Latence",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "API REST",
        "c09_title": "GraphQL",
        "c10_title": "Bases de Donn\u00e9es",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Mise \u00e0 l'\u00e9chelle Verticale",
        "c13_title": "Mise \u00e0 l'\u00e9chelle Horizontale",
        "c14_title": "\u00c9quilibreurs de Charge",
        "c15_title": "Indexation de Base de Donn\u00e9es",
        "c16_title": "R\u00e9plication",
        "c17_title": "Sharding",
        "c18_title": "Partitionnement Vertical",
        "c19_title": "Mise en Cache",
        "c20_title": "D\u00e9normalisation",
        "c21_title": "Th\u00e9or\u00e8me CAP",
        "c22_title": "Stockage d'Objets (Blob)",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservices",
        "c27_title": "Files d'Attente de Messages",
        "c28_title": "Limitation de D\u00e9bit",
        "c29_title": "Passerelles API",
        "c30_title": "Idempotence"
    },
    "pt": {
        "main_title": "Conceitos de Design de Sistemas",
        "main_subtitle": "30 Conceitos fundamentais visualizados e animados.",
        "nav_back": "Voltar ao In\u00edcio",
        "nav_prev": "Anterior",
        "nav_next": "Pr\u00f3ximo",
        "viz_placeholder": "Em Breve",
        "c01_title": "Arquitetura Cliente-Servidor",
        "c02_title": "Endere\u00e7o IP",
        "c03_title": "DNS",
        "c04_title": "Proxy / Proxy Reverso",
        "c05_title": "Lat\u00eancia",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "API REST",
        "c09_title": "GraphQL",
        "c10_title": "Bancos de Dados",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Escalonamento Vertical",
        "c13_title": "Escalonamento Horizontal",
        "c14_title": "Balanceadores de Carga",
        "c15_title": "Indexa\u00e7\u00e3o de Banco de Dados",
        "c16_title": "Replica\u00e7\u00e3o",
        "c17_title": "Sharding",
        "c18_title": "Particionamento Vertical",
        "c19_title": "Cache",
        "c20_title": "Desnormaliza\u00e7\u00e3o",
        "c21_title": "Teorema CAP",
        "c22_title": "Armazenamento de Blob",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microsservi\u00e7os",
        "c27_title": "Filas de Mensagens",
        "c28_title": "Rate Limiting",
        "c29_title": "Gateways de API",
        "c30_title": "Idempot\u00eancia"
    }
};
window.translations = translations;