const translations = {
    "en": {
        "main_title": "System Design Concepts",
        "main_subtitle": "30 Fundamental concepts visualized and animated.",
        "nav_back": "Back to Concepts",
        "nav_prev": "Previous",
        "nav_next": "Next",
        "viz_placeholder": "Visuals Coming Soon",
        "c01_title": "Client-Server Architecture",
        "c01_desc": "The fundamental architectural pattern of the web. It separates concerns into two distinct parties:",
        "c01_client": "<strong>Client:</strong> The requester (Browser, Mobile App). It initiates communication.",
        "c01_server": "<strong>Server:</strong> The provider. It processes requests and returns resources (HTML, JSON, Files).",
        "c01_note": "Communication typically happens over HTTP/HTTPS. Ideally, the client doesn't need to know how the server works, just how to ask for what it wants (API).",
        "c01_viz_client": "Client",
        "c01_viz_server": "Server",
        "c01_viz_send": "Send Request",
        "c01_viz_processing": "Processing...",
        "c02_title": "IP Address",
        "c02_desc_1": "An <strong>Internet Protocol (IP) Address</strong> is a unique address that identifies a device on the internet or a local network.",
        "c02_desc_2": "Think of it like a <strong>House Address</strong>. To receive mail (data packets), you need a specific location that the sender can target.",
        "c02_ipv4": "<strong>IPv4:</strong> Four sets of numbers (e.g., 192.168.1.1) - most common.",
        "c02_ipv6": "<strong>IPv6:</strong> Longer, hexadecimal format to accommodate more devices.",
        "c02_viz_target": "Target",
        "c02_viz_send": "Send to 192.168.1.11",
        "c03_title": "DNS",
        "c03_desc_1": "<strong>Domain Name System (DNS)</strong> is the phonebook of the internet. Humans access information online through domain names like <em>google.com</em> or <em>espn.com</em>. Web browsers interact through Internet Protocol (IP) addresses.",
        "c03_desc_2": "DNS translates domain names to IP addresses so browsers can load Internet resources.",
        "c03_viz_resolver": "DNS Resolver",
        "c03_viz_lookup": "Looking up...",
        "c03_viz_resolve": "Resolve Domain",
        "c04_title": "Proxy / Reverse Proxy",
        "c04_desc": "An intermediary server that sits between client and server.",
        "c04_fwd_title": "Forward Proxy",
        "c04_fwd_desc": "Sits before the client. Hides the client's identity from the server. (e.g. VPN, School Filter)",
        "c04_rev_title": "Reverse Proxy",
        "c04_rev_desc": "Sits before the server. Hides the server's identity from the client. (e.g. Load Balancer, CDN, Security)",
        "c04_btn_fwd": "Forward Proxy",
        "c04_btn_rev": "Reverse Proxy",
        "c04_viz_client": "Client",
        "c04_viz_proxy": "Proxy",
        "c04_viz_server": "Internet/Server",
        "c04_viz_expl": "The Server sees the Proxy IP, not the Client IP.",
        "c04_viz_sim": "Simulate Request",
        "c05_title": "Latency",
        "c05_desc_1": "<strong>Latency</strong> is the time it takes for data to travel from its source to its destination. It is often measured in milliseconds (ms).",
        "c05_desc_2": "High latency = Slow response (Lag).<br>Low latency = Fast response.",
        "c05_note": "Factors affecting latency: Distance, Network Congestion, Protocol overhead.",
        "c05_viz_nearby": "Nearby Server (CDN)",
        "c05_viz_distant": "Distant Server (Overseas)",
        "c05_viz_ping": "Ping Servers",
        "c06_title": "HTTP/HTTPS",
        "c06_desc_http": "<strong>HTTP (Hypertext Transfer Protocol)</strong> is the foundation of data communication on the web. It transmits data in <strong>plain text</strong>, meaning anyone intercepting it can read it.",
        "c06_desc_https": "<strong>HTTPS (S = Secure)</strong> uses TLS/SSL to <strong>encrypt</strong> the communication. Only the sender and receiver have the keys to decrypt the data.",
        "c06_note": "Always use HTTPS for sensitive data (Passwords, Credit Cards).",
        "c06_btn_http": "HTTP (Insecure)",
        "c06_btn_https": "HTTPS (Secure)",
        "c06_viz_hacker": "I hacked: password123",
        "c06_viz_send": "Send Data",
        "c07_title": "APIs",
        "c07_desc_1": "<strong>API (Application Programming Interface)</strong> is a set of rules that allows different software applications to communicate with each other.",
        "c07_desc_2": "The classic analogy is a <strong>Restaurant</strong>:",
        "c07_list_client": "<strong>You (Client):</strong> You want food (data/service), but you can't go into the kitchen.",
        "c07_list_waiter": "<strong>Waiter (API):</strong> Takes your order, sends it to the kitchen, and brings you the food.",
        "c07_list_kitchen": "<strong>Kitchen (System):</strong> Prepares the food described in the order.",
        "c07_viz_cust": "Customer",
        "c07_viz_waiter": "API (Waiter)",
        "c07_viz_order": "📝 Order",
        "c07_viz_kitchen": "System (Kitchen)",
        "c07_viz_status": "Waiting for order...",
        "c07_viz_btn": "Place Order",
        "c08_title": "REST API",
        "c08_desc": "<strong>REST (Representational State Transfer)</strong> is a popular architectural style for APIs. It uses standard HTTP methods to perform actions on resources (data objects).",
        "c08_get": "Retrieve a resource (Read).",
        "c08_post": "Create a new resource.",
        "c08_put": "Update an existing resource (Replace).",
        "c08_delete": "Remove a resource.",
        "c08_viz_db": "Database Resources",
        "c08_viz_ready": "Ready...",
        "c09_title": "GraphQL",
        "c09_desc_1": "<strong>GraphQL</strong> is a query language for APIs. Unlike REST, where you often get too much or too little data (Over/Under fetching), GraphQL allows the client to ask for <strong>exactly what they need</strong>.",
        "c09_desc_2": "\"Give me just the name and age.\" -> Server returns just the name and age.",
        "c09_viz_query": "Query",
        "c09_viz_resp": "Response (JSON)",
        "c10_title": "Databases",
        "c10_desc_1": "A <strong>Database</strong> is a system for authorized collection of data. It allows for efficient storage, retrieval, and modification of data.",
        "c10_desc_2": "Web servers are typically \"stateless\" (they forget everything after a request). Databases provide <strong>persistence</strong> (memories that last).",
        "c10_viz_app": "App Server",
        "c10_viz_db": "Database",
        "c10_viz_write": "Write Data",
        "c10_viz_read": "Read Data",
        "c11_title": "SQL vs NoSQL",
        "c11_desc_1": "<strong>SQL (Relational)</strong>: Data is stored in tables with fixed schemas. Good for complex relationships and consistency.",
        "c11_desc_2": "<strong>NoSQL (Non-Relational)</strong>: Data is stored in flexible documents (JSON). Good for rapid growth, unstructured data, and scaling.",
        "c11_btn_sql": "SQL (Tables)",
        "c11_btn_nosql": "NoSQL (JSON)",
        "c12_title": "Vertical Scaling",
        "c12_desc_1": "When a system gets more traffic, it needs to scale.",
        "c12_desc_2": "<strong>Vertical Scaling (Scale Up)</strong>",
        "c12_desc_3": "Adding more power (CPU, RAM) to an existing machine. <br><em>\"Buy a bigger machine.\"</em>",
        "c12_viz_pool": "Server Pool",
        "c12_viz_power": "1x Power",
        "c12_viz_btn_scale": "Vertical Scale (+Power)",
        "c12_viz_btn_reset": "Reset",
        "c13_title": "Horizontal Scaling",
        "c13_desc_1": "When a system gets more traffic, it needs to scale.",
        "c13_desc_2": "<strong>Horizontal Scaling (Scale Out)</strong>",
        "c13_desc_3": "Adding more machines to the pool. <br><em>\"Buy more machines.\"</em>",
        "c13_viz_btn_scale": "Horizontal Scale (+Unit)",
        "c14_title": "Load Balancers",
        "c14_desc_1": "A <strong>Load Balancer</strong> distributes incoming network traffic across multiple servers. This ensures no single server bears too much load.",
        "c14_desc_2": "It prevents server crashes due to high traffic and improves overall availability.",
        "c14_note": "Algorithm shown: <strong>Round Robin</strong> (Sequential distribution).",
        "c14_viz_incoming": "Incoming Traffic",
        "c14_viz_lb": "Load Balancer",
        "c14_server": "Server",
        "c14_btn_1": "Add 1 Request",
        "c14_btn_5": "Add 5 Requests (Burst)",
        "c15_title": "Database Indexing",
        "c15_desc": "<strong>Database Indexing</strong> is a data structure technique used to quickly locate and access the data in a database.<br><br>It's like the index at the back of a book: instead of reading every page (Full Table Scan) to find a topic, you look it up in the index to find the exact page number (Index Seek).",
        "c15_btn_full": "Full Table Scan",
        "c15_btn_index": "Index Seek",
        "c15_status_ready": "Ready",
        "c16_title": "Replication",
        "c16_desc": "<strong>Replication</strong> involves strictly copying data from one database node (primary) to one or more nodes (replicas).<br><br>This increases <strong>Availability</strong> (if one fails, others work) and <strong>Read Performance</strong> (reads can be spread across replicas).",
        "c16_primary": "Primary",
        "c16_replica": "Replica",
        "c16_btn_write": "Write Data",
        "c17_title": "Sharding",
        "c17_desc": "<strong>Sharding</strong> (Horizontal Partitioning) is splitting a large dataset across multiple databases (shards) based on a key (e.g., UserID).<br><br>Each shard holds a unique subset of data, allowing the system to handle massive amounts of data and writes.",
        "c17_viz_ph": "User ID (1-100)",
        "c17_viz_save": "Save User",
        "c17_viz_shard_a": "Shard A (Odd)",
        "c17_viz_shard_b": "Shard B (Even)",
        "c18_title": "Vertical Partitioning",
        "c18_desc": "<strong>Vertical Partitioning</strong> involves splitting a table by columns.<br><br>For example, storing frequently accessed columns (username, status) in one table and heavy, rarely used columns (bio, profile_image_blob) in another.",
        "c18_viz_big": "User Table (Big)",
        "c18_viz_split": "✂️ Split",
        "c18_viz_core": "Core (Fast)",
        "c18_viz_meta": "Meta (Slow)",
        "c19_title": "Caching",
        "c19_desc_1": "<strong>Caching</strong> is using a high-speed data storage layer (RAM) to store a subset of data so that future requests for that data are served faster.",
        "c19_desc_2": "It's like keeping your most used tools on your belt instead of walking to the garage (Database) every time you need them.",
        "c19_list_hit": "<span class=\"status-badge hit\">Cache Hit</span> Data found in cache (Fast)",
        "c19_list_miss": "<span class=\"status-badge miss\">Cache Miss</span> Data not in cache, fetch from DB (Slow)",
        "c19_viz_user": "User",
        "c19_viz_cache": "Cache (RAM)",
        "c19_viz_db": "Database (Disk)",
        "c19_btn_a": "Request 'A'",
        "c19_btn_b": "Request 'B'",
        "c20_title": "Denormalization",
        "c20_desc": "<strong>Denormalization</strong> is the process of adding redundant data to a database to speed up reads.<br><br>Instead of performing expensive JOINS on every read, you store the joined data in a single table, trading write speed and storage for faster reads.",
        "c20_btn_run": "Run Query",
        "c20_status_wait": "Waiting...",
        "c20_viz_norm_title": "Normalized (JOIN)",
        "c20_viz_norm_desc": "Users Table + Orders Table",
        "c20_viz_denorm_title": "Denormalized (Single)",
        "c20_viz_denorm_desc": "UsersOrders Table",
        "c21_title": "CAP Theorem",
        "c22_title": "Blob Storage",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservices",
        "c27_title": "Message Queues",
        "c28_title": "Rate Limiting",
        "c29_title": "API Gateways",
        "c30_title": "Idempotency",
        "c21_title": "CAP Theorem",
        "c21_desc": "The <strong>CAP Theorem</strong> states that a distributed system can only provide two of the following three guarantees:<br><br>1. <strong>Consistency</strong> (Every read receives the most recent write)<br>2. <strong>Availability</strong> (Every request receives a response)<br>3. <strong>Partition Tolerance</strong> (System continues to work despite network failures)",
        "c21_viz_c": "Consistency",
        "c21_viz_a": "Availability",
        "c21_viz_p": "Partition Tolerance",
        "c21_viz_msg": "Pick 2 (Usually P + C or A)",
        "c21_btn_cp": "CP",
        "c21_btn_ap": "AP",
        "c21_btn_ca": "CA (Rare)",
        "c22_desc": "<strong>Blob (Binary Large Object) Storage</strong> is optimized for storing unstructured data like images, videos, logs, and backups.<br><br>Examples: AWS S3, Google Cloud Storage, Azure Blob Storage.",
        "c22_viz_bucket": "🪣 S3 Bucket",
        "c22_viz_upload": "Upload File",
        "c23_desc_1": "<strong>CDN (Content Delivery Network)</strong> is a geographically distributed network of proxy servers. Its goal is to provide high availability and performance by distributing the service spatially relative to end-users.",
        "c23_desc_2": "Instead of everyone downloading a video from one server in New York, users in London download it from a server in London.",
        "c23_viz_origin": "🇺🇸 Origin",
        "c23_viz_edge_eu": "🇪🇺 Edge",
        "c23_viz_edge_asia": "🇯🇵 Edge",
        "c23_viz_user_us": "User (USA)",
        "c23_viz_user_eu": "User (EU)",
        "c23_viz_user_asia": "User (Asia)",
        "c23_viz_mode": "Mode:",
        "c23_btn_no_cdn": "Without CDN",
        "c23_btn_cdn": "With CDN",
        "c23_btn_start": "Start Download",
        "c24_desc": "<strong>WebSockets</strong> provide a persistent, full-duplex communication channel over a single TCP connection.<br><br>Ideally used for real-time applications like Chat Apps, Live Sports Scores, or Collaborative Editing.",
        "c24_viz_client": "Client",
        "c24_viz_server": "Server",
        "c24_btn_client": "Client Msg",
        "c24_btn_server": "Server Msg",
        "c25_desc": "<strong>Webhooks</strong> are user-defined HTTP callbacks.<br><br>Instead of your app polling an API (\"Is it done yet?\"), the service sends a POST request to your app when an event occurs (\"It's done!\").",
        "c25_viz_provider": "Provider (GitHub)",
        "c25_viz_consumer": "Your App",
        "c25_btn_trigger": "Trigger Event (Push)",
        "c26_desc": "<strong>Microservices</strong> architecture structures an application as a collection of loosely coupled services.<br><br>Each service is <br>- Highly maintainable and testable<br>- Independently deployable<br>- Organized around business capabilities.",
        "c26_viz_svc_auth": "Auth Svc",
        "c26_viz_svc_order": "Order Svc",
        "c26_viz_svc_pay": "Pay Svc",
        "c26_viz_svc_user": "User Svc",
        "c26_viz_text": "Independent, Decentralized",
        "c27_desc": "A <strong>Message Queue</strong> buffers requests between services for asynchronous processing.<br><br>Producers send messages to the queue, and Consumers process them at their own pace. This decouples services and handles load spikes.",
        "c27_viz_prod": "Producer",
        "c27_viz_cons": "Consumer",
        "c27_btn_prod": "Produce Msg",
        "c27_btn_cons": "Consume Msg",
        "c28_desc": "<strong>Rate Limiting</strong> controls the number of requests a user or client can send to an API in a given timeframe.<br><br>It protects the system from Denial of Service (DoS) attacks and prevents overuse of resources.",
        "c28_viz_gate": "Gate",
        "c28_btn_send": "Send Rapid Requests",
        "c28_limit_text": "limit",
        "c29_desc": "An <strong>API Gateway</strong> sits between the client and the backend services.<br><br>It handles cross-cutting concerns like:<br>- Authentication & Authorization<br>- Rate Limiting<br>- Request Routing / Load Balancing",
        "c29_viz_user": "User",
        "c29_viz_gw": "Gateway",
        "c29_btn_a": "Route to A",
        "c29_btn_b": "Route to B",
        "c30_desc": "<strong>Idempotency</strong> means that making the same request multiple times has the same effect as making it once.<br><br>Crucial for payment systems: If a user clicks 'Pay' twice, they should only be charged once.",
        "c30_btn_pay": "PAY $10",
        "c30_lbl_charges": "Charges:",
        "c30_lbl_balance": "Balance Deducted:"
    },
    "es": {
        "main_title": "Conceptos de Diseño de Sistemas",
        "main_subtitle": "30 Conceptos fundamentales visualizados y animados.",
        "nav_back": "Volver al Inicio",
        "nav_prev": "Anterior",
        "nav_next": "Siguiente",
        "viz_placeholder": "Visualización Próximamente",
        "c01_title": "Arquitectura Cliente-Servidor",
        "c01_desc": "El patrón arquitectónico fundamental de la web. Separa las responsabilidades en dos partes distintas:",
        "c01_client": "<strong>Cliente:</strong> El solicitante (Navegador, App Móvil). Inicia la comunicación.",
        "c01_server": "<strong>Servidor:</strong> El proveedor. Procesa las solicitudes y devuelve recursos (HTML, JSON, Archivos).",
        "c01_note": "La comunicación suele ocurrir sobre HTTP/HTTPS. Idealmente, el cliente no necesita saber cómo funciona el servidor, solo cómo pedir lo que quiere (API).",
        "c01_viz_client": "Cliente",
        "c01_viz_server": "Servidor",
        "c01_viz_send": "Enviar Solicitud",
        "c01_viz_processing": "Procesando...",
        "c02_title": "Dirección IP",
        "c02_desc_1": "Una <strong>Dirección de Protocolo de Internet (IP)</strong> es una dirección única que identifica un dispositivo en internet o en una red local.",
        "c02_desc_2": "Piense en ello como una <strong>Dirección de Casa</strong>. Para recibir correo (paquetes de datos), necesita una ubicación específica a la que el remitente pueda dirigirse.",
        "c02_ipv4": "<strong>IPv4:</strong> Cuatro conjuntos de números (ej. 192.168.1.1) - el más común.",
        "c02_ipv6": "<strong>IPv6:</strong> Formato hexadecimal más largo para acomodar más dispositivos.",
        "c02_viz_target": "Destino",
        "c02_viz_send": "Enviar a 192.168.1.11",
        "c03_title": "DNS",
        "c03_desc_1": "El <strong>Sistema de Nombres de Dominio (DNS)</strong> es la guía telefónica de internet. Los humanos acceden a la información a través de nombres de dominio como <em>google.com</em> o <em>espn.com</em>. Los navegadores web interactúan mediante direcciones IP.",
        "c03_desc_2": "El DNS traduce los nombres de dominio a direcciones IP para que los navegadores puedan cargar los recursos de Internet.",
        "c03_viz_resolver": "Resolutor DNS",
        "c03_viz_lookup": "Buscando...",
        "c03_viz_resolve": "Resolver Dominio",
        "c04_title": "Proxy / Proxy Inverso",
        "c04_desc": "Un servidor intermediario que se sitúa entre el cliente y el servidor.",
        "c04_fwd_title": "Proxy Directo (Forward)",
        "c04_fwd_desc": "Se sitúa ante el cliente. Oculta la identidad del cliente al servidor. (ej. VPN, Filtro Escolar)",
        "c04_rev_title": "Proxy Inverso (Reverse)",
        "c04_rev_desc": "Se sitúa ante el servidor. Oculta la identidad del servidor al cliente. (ej. Load Balancer, CDN, Seguridad)",
        "c04_btn_fwd": "Proxy Directo",
        "c04_btn_rev": "Proxy Inverso",
        "c04_viz_client": "Cliente",
        "c04_viz_proxy": "Proxy",
        "c04_viz_server": "Internet/Servidor",
        "c04_viz_expl": "El Servidor ve la IP del Proxy, no la IP del Cliente.",
        "c04_viz_sim": "Simular Solicitud",
        "c05_title": "Latencia",
        "c05_desc_1": "La <strong>Latencia</strong> es el tiempo que tardan los datos en viajar desde su origen hasta su destino. A menudo se mide en milisegundos (ms).",
        "c05_desc_2": "Alta latencia = Respuesta lenta (Lag).<br>Baja latencia = Respuesta rápida.",
        "c05_note": "Factores que afectan la latencia: Distancia, Congestión de red, Sobrecarga de protocolo.",
        "c05_viz_nearby": "Servidor Cercano (CDN)",
        "c05_viz_distant": "Servidor Lejano (Ultramar)",
        "c05_viz_ping": "Hacer Ping",
        "c06_title": "HTTP/HTTPS",
        "c06_desc_http": "<strong>HTTP (Protocolo de Transferencia de Hipertexto)</strong> es la base de la comunicación de datos en la web. Transmite datos en <strong>texto plano</strong>, lo que significa que cualquiera que lo intercepte puede leerlo.",
        "c06_desc_https": "<strong>HTTPS (S = Seguro)</strong> utiliza TLS/SSL para <strong>cifrar</strong> la comunicación. Solo el remitente y el receptor tienen las claves para descifrar los datos.",
        "c06_note": "Utilice siempre HTTPS para datos sensibles (Contraseñas, Tarjetas de Crédito).",
        "c06_btn_http": "HTTP (Inseguro)",
        "c06_btn_https": "HTTPS (Seguro)",
        "c06_viz_hacker": "Hackeado: password123",
        "c06_viz_send": "Enviar Datos",
        "c07_title": "APIs",
        "c07_desc_1": "<strong>API (Interfaz de Programación de Aplicaciones)</strong> es un conjunto de reglas que permite que diferentes aplicaciones de software se comuniquen entre sí.",
        "c07_desc_2": "La analogía clásica es un <strong>Restaurante</strong>:",
        "c07_list_client": "<strong>Tú (Cliente):</strong> Quieres comida (datos/servicio), pero no puedes entrar a la cocina.",
        "c07_list_waiter": "<strong>Mesero (API):</strong> Toma tu pedido, lo envía a la cocina y te trae la comida.",
        "c07_list_kitchen": "<strong>Cocina (Sistema):</strong> Prepara la comida descrita en el pedido.",
        "c07_viz_cust": "Cliente",
        "c07_viz_waiter": "API (Mesero)",
        "c07_viz_order": "📝 Pedido",
        "c07_viz_kitchen": "Sistema (Cocina)",
        "c07_viz_status": "Esperando pedido...",
        "c07_viz_btn": "Realizar Pedido",
        "c08_title": "API REST",
        "c08_desc": "<strong>REST (Transferencia de Estado Representacional)</strong> es un estilo arquitectónico popular para APIs. Utiliza métodos HTTP estándar para realizar acciones sobre recursos (objetos de datos).",
        "c08_get": "Recuperar un recurso (Leer).",
        "c08_post": "Crear un nuevo recurso.",
        "c08_put": "Actualizar un recurso existente (Reemplazar).",
        "c08_delete": "Eliminar un recurso.",
        "c08_viz_db": "Recursos de Base de Datos",
        "c08_viz_ready": "Listo...",
        "c09_title": "GraphQL",
        "c09_desc_1": "<strong>GraphQL</strong> es un lenguaje de consulta para APIs. A diferencia de REST, donde a menudo obtienes demasiados o muy pocos datos (Over/Under fetching), GraphQL permite al cliente pedir <strong>exactamente lo que necesita</strong>.",
        "c09_desc_2": "\"Dame solo el nombre y la edad.\" -> El servidor devuelve solo el nombre y la edad.",
        "c09_viz_query": "Consulta (Query)",
        "c09_viz_resp": "Respuesta (JSON)",
        "c10_title": "Bases de Datos",
        "c10_desc_1": "Una <strong>Base de Datos</strong> es un sistema para la recolección autorizada de datos. Permite el almacenamiento, recuperación y modificación eficiente de datos.",
        "c10_desc_2": "Los servidores web suelen ser \"sin estado\" (olvidan todo después de una solicitud). Las bases de datos proporcionan <strong>persistencia</strong> (memorias que perduran).",
        "c10_viz_app": "Servidor App",
        "c10_viz_db": "Base de Datos",
        "c10_viz_write": "Escribir Datos",
        "c10_viz_read": "Leer Datos",
        "c11_title": "SQL vs NoSQL",
        "c11_desc_1": "<strong>SQL (Relacional)</strong>: Los datos se almacenan en tablas con esquemas fijos. Bueno para relaciones complejas y consistencia.",
        "c11_desc_2": "<strong>NoSQL (No Relacional)</strong>: Los datos se almacenan en documentos flexibles (JSON). Bueno para crecimiento rápido, datos no estructurados y escalado.",
        "c11_btn_sql": "SQL (Tablas)",
        "c11_btn_nosql": "NoSQL (JSON)",
        "c12_title": "Escalado Vertical",
        "c12_desc_1": "Cuando un sistema recibe más tráfico, necesita escalar.",
        "c12_desc_2": "<strong>Escalado Vertical (Scale Up)</strong>",
        "c12_desc_3": "Añadir más potencia (CPU, RAM) a una máquina existente. <br><em>\"Comprar una máquina más grande.\"</em>",
        "c12_viz_pool": "Pool de Servidores",
        "c12_viz_power": "1x Potencia",
        "c12_viz_btn_scale": "Escalar Vertical (+Potencia)",
        "c12_viz_btn_reset": "Reiniciar",
        "c13_title": "Escalado Horizontal",
        "c13_desc_1": "Cuando un sistema recibe más tráfico, necesita escalar.",
        "c13_desc_2": "<strong>Escalado Horizontal (Scale Out)</strong>",
        "c13_desc_3": "Añadir más máquinas al pool. <br><em>\"Comprar más máquinas.\"</em>",
        "c13_viz_btn_scale": "Escalar Horizontal (+Unidad)",
        "c14_title": "Balanceadores de Carga",
        "c14_desc_1": "Un <strong>Balanceador de Carga</strong> distribuye el tráfico de red entrante entre múltiples servidores. Esto asegura que ningún servidor soporte demasiada carga.",
        "c14_desc_2": "Evita caídas del servidor debido al alto tráfico y mejora la disponibilidad general.",
        "c14_note": "Algoritmo mostrado: <strong>Round Robin</strong> (Distribución secuencial).",
        "c14_viz_incoming": "Tráfico Entrante",
        "c14_viz_lb": "Balanceador de Carga",
        "c14_server": "Servidor",
        "c14_btn_1": "Añadir 1 Petición",
        "c14_btn_5": "Añadir 5 Peticiones (Ráfaga)",
        "c15_title": "Índices de Base de Datos",
        "c15_desc": "La <strong>Indexación de Base de Datos</strong> es una técnica de estructura de datos utilizada para localizar y acceder rápidamente a los datos en una base de datos.<br><br>Es como el índice al final de un libro: en lugar de leer cada página (Full Table Scan) para encontrar un tema, lo buscas en el índice para encontrar el número exacto de página (Index Seek).",
        "c15_btn_full": "Escaneo Completo (Full Scan)",
        "c15_btn_index": "Búsqueda por Índice (Index Seek)",
        "c15_status_ready": "Listo",
        "c16_title": "Replicación",
        "c16_desc": "La <strong>Replicación</strong> implica copiar estrictamente datos de un nodo de base de datos (primario) a uno o más nodos (réplicas).<br><br>Esto aumenta la <strong>Disponibilidad</strong> (si uno falla, los otros funcionan) y el <strong>Rendimiento de Lectura</strong> (las lecturas se pueden repartir entre las réplicas).",
        "c16_primary": "Primario",
        "c16_replica": "Réplica",
        "c16_btn_write": "Escribir Datos",
        "c17_title": "Sharding (Fragmentación)",
        "c17_desc": "<strong>Sharding</strong> (Particionamiento Horizontal) es dividir un gran conjunto de datos entre múltiples bases de datos (shards) basado en una clave (ej. UserID).<br><br>Cada shard contiene un subconjunto único de datos, permitiendo al sistema manejar cantidades masivas de datos y escrituras.",
        "c17_viz_ph": "User ID (1-100)",
        "c17_viz_save": "Guardar Usuario",
        "c17_viz_shard_a": "Shard A (Impar)",
        "c17_viz_shard_b": "Shard B (Par)",
        "c18_title": "Particionamiento Vertical",
        "c18_desc": "El <strong>Particionamiento Vertical</strong> implica dividir una tabla por columnas.<br><br>Por ejemplo, almacenar columnas frecuentemente accedidas (username, status) en una tabla y columnas pesadas y raramente usadas (bio, profile_image_blob) en otra.",
        "c18_viz_big": "Tabla Usuario (Grande)",
        "c18_viz_split": "✂️ Dividir",
        "c18_viz_core": "Núcleo (Rápido)",
        "c18_viz_meta": "Meta (Lento)",
        "c19_title": "Caché",
        "c19_desc_1": "<strong>Caching</strong> es usar una capa de almacenamiento de datos de alta velocidad (RAM) para almacenar un subconjunto de datos para que las futuras solicitudes de esos datos se sirvan más rápido.",
        "c19_desc_2": "Es como tener tus herramientas a mano en tu cinturón en lugar de caminar al garaje (Base de Datos) cada vez que las necesitas.",
        "c19_list_hit": "<span class=\"status-badge hit\">Cache Hit</span> Datos en caché (Rápido)",
        "c19_list_miss": "<span class=\"status-badge miss\">Cache Miss</span> Datos no en caché, buscar en BD (Lento)",
        "c19_viz_user": "Usuario",
        "c19_viz_cache": "Caché (RAM)",
        "c19_viz_db": "Base de Datos (Disco)",
        "c19_btn_a": "Solicitar 'A'",
        "c19_btn_b": "Solicitar 'B'",
        "c20_title": "Desnormalización",
        "c20_desc": "La <strong>Desnormalización</strong> es el proceso de añadir datos redundantes a una base de datos para acelerar las lecturas.<br><br>En lugar de realizar costosos JOINS en cada lectura, almacenas los datos unidos en una sola tabla, intercambiando velocidad de escritura y almacenamiento por lecturas más rápidas.",
        "c20_btn_run": "Ejecutar Query",
        "c20_status_wait": "Esperando...",
        "c20_viz_norm_title": "Normalizado (JOIN)",
        "c20_viz_norm_desc": "Tabla Usuarios + Tabla Pedidos",
        "c20_viz_denorm_title": "Desnormalizado (Único)",
        "c20_viz_denorm_desc": "Tabla UsuariosPedidos",
        "c21_title": "Teorema CAP",
        "c22_title": "Almacenamiento de Blobs",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservicios",
        "c27_title": "Colas de Mensajes",
        "c28_title": "Rate Limiting (Limitador)",
        "c29_title": "API Gateways",
        "c30_title": "Idempotencia",
        "c21_desc": "El <strong>Teorema CAP</strong> afirma que un sistema distribuido solo puede garantizar dos de las tres siguientes propiedades:<br><br>1. <strong>Consistencia</strong> (Cada lectura recibe la escritura más reciente)<br>2. <strong>Disponibilidad</strong> (Cada solicitud recibe una respuesta)<br>3. <strong>Tolerancia a Particiones</strong> (El sistema sigue funcionando a pesar de fallos en la red)",
        "c21_viz_c": "Consistencia",
        "c21_viz_a": "Disponibilidad",
        "c21_viz_p": "Tolerancia a Particiones",
        "c21_viz_msg": "Elige 2 (Usualmente P + C o A)",
        "c21_btn_cp": "CP",
        "c21_btn_ap": "AP",
        "c21_btn_ca": "CA (Raro)",
        "c22_desc": "El <strong>Almacenamiento de Blobs (Objetos Binarios Grandes)</strong> está optimizado para almacenar datos no estructurados como imágenes, videos, logs y copias de seguridad.<br><br>Ejemplos: AWS S3, Google Cloud Storage, Azure Blob Storage.",
        "c22_viz_bucket": "🪣 Bucket S3",
        "c22_viz_upload": "Subir Archivo",
        "c23_desc_1": "<strong>CDN (Red de Distribución de Contenido)</strong> es una red distribuida geográficamente de servidores proxy. Su objetivo es proporcionar alta disponibilidad y rendimiento distribuyendo el servicio espacialmente en relación con los usuarios finales.",
        "c23_desc_2": "En lugar de que todos descarguen un video de un servidor en Nueva York, los usuarios en Londres lo descargan de un servidor en Londres.",
        "c23_viz_origin": "🇺🇸 Origen",
        "c23_viz_edge_eu": "🇪🇺 Borde (EU)",
        "c23_viz_edge_asia": "🇯🇵 Borde (Asia)",
        "c23_viz_user_us": "Usuario (USA)",
        "c23_viz_user_eu": "Usuario (EU)",
        "c23_viz_user_asia": "Usuario (Asia)",
        "c23_viz_mode": "Modo:",
        "c23_btn_no_cdn": "Sin CDN",
        "c23_btn_cdn": "Con CDN",
        "c23_btn_start": "Iniciar Descarga",
        "c24_desc": "<strong>WebSockets</strong> proporcionan un canal de comunicación full-duplex persistente sobre una única conexión TCP.<br><br>Ideal para aplicaciones en tiempo real como Chats, Resultados Deportivos en Vivo o Edición Colaborativa.",
        "c24_viz_client": "Cliente",
        "c24_viz_server": "Servidor",
        "c24_btn_client": "Msj Cliente",
        "c24_btn_server": "Msj Servidor",
        "c25_desc": "Los <strong>Webhooks</strong> son callbacks HTTP definidos por el usuario.<br><br>En lugar de que tu app pregunte a una API (\"¿Ya terminaste?\"), el servicio envía una solicitud POST a tu app cuando ocurre un evento (\"¡Terminado!\").",
        "c25_viz_provider": "Proveedor (GitHub)",
        "c25_viz_consumer": "Tu App",
        "c25_btn_trigger": "Disparar Evento (Push)",
        "c26_desc": "La arquitectura de <strong>Microservicios</strong> estructura una aplicación como una colección de servicios débilmente acoplados.<br><br>Cada servicio es <br>- Altamente mantenible y testearle<br>- Desplegable independientemente<br>- Organizado en torno a capacidades de negocio.",
        "c26_viz_svc_auth": "Svc Auth",
        "c26_viz_svc_order": "Svc Pedidos",
        "c26_viz_svc_pay": "Svc Pagos",
        "c26_viz_svc_user": "Svc Usuario",
        "c26_viz_text": "Independiente, Descentralizado",
        "c27_desc": "Una <strong>Cola de Mensajes</strong> amortigua las solicitudes entre servicios para el procesamiento asíncrono.<br><br>Los Productores envían mensajes a la cola, y los Consumidores los procesan a su propio ritmo. Esto desacopla los servicios y maneja picos de carga.",
        "c27_viz_prod": "Productor",
        "c27_viz_cons": "Consumidor",
        "c27_btn_prod": "Producir Msj",
        "c27_btn_cons": "Consumir Msj",
        "c28_desc": "<strong>Rate Limiting</strong> controla el número de solicitudes que un usuario o cliente puede enviar a una API en un periodo de tiempo determinado.<br><br>Protege el sistema de ataques de Denegación de Servicio (DoS) y previene el uso excesivo de recursos.",
        "c28_viz_gate": "Puerta",
        "c28_btn_send": "Enviar Peticiones Rápidas",
        "c28_limit_text": "límite",
        "c29_desc": "Un <strong>API Gateway</strong> se sitúa entre el cliente y los servicios backend.<br><br>Maneja preocupaciones transversales como:<br>- Autenticación y Autorización<br>- Rate Limiting<br>- Enrutamiento de Solicitudes / Balanceo de Carga",
        "c29_viz_user": "Usuario",
        "c29_viz_gw": "Gateway",
        "c29_btn_a": "Enrutar a A",
        "c29_btn_b": "Enrutar a B",
        "c30_desc": "<strong>Idempotencia</strong> significa que hacer la misma solicitud múltiples veces tiene el mismo efecto que hacerla una sola vez.<br><br>Crucial para sistemas de pago: Si un usuario hace clic en 'Pagar' dos veces, solo se le debe cobrar una vez.",
        "c30_btn_pay": "PAGAR $10",
        "c30_lbl_charges": "Cargos:",
        "c30_lbl_balance": "Saldo Deducido:"
    },
    "fr": {
        "main_title": "Concepts de Conception de Systèmes",
        "main_subtitle": "30 Concepts fondamentaux visualisés et animés.",
        "nav_back": "Retour à l'accueil",
        "nav_prev": "Précédent",
        "nav_next": "Suivant",
        "viz_placeholder": "Bientôt Disponible",
        "c01_title": "Architecture Client-Serveur",
        "c02_title": "Adresse IP",
        "c03_title": "DNS",
        "c04_title": "Proxy / Reverse Proxy",
        "c05_title": "Latence",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "API REST",
        "c09_title": "GraphQL",
        "c10_title": "Bases de Données",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Mise à l'échelle Verticale",
        "c13_title": "Mise à l'échelle Horizontale",
        "c14_title": "Équilibreurs de Charge",
        "c15_title": "Indexation de Base de Données",
        "c16_title": "Réplication",
        "c17_title": "Sharding",
        "c18_title": "Partitionnement Vertical",
        "c19_title": "Mise en Cache",
        "c20_title": "Dénormalisation",
        "c21_title": "Théorème CAP",
        "c22_title": "Stockage d'Objets (Blob)",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microservices",
        "c27_title": "Files d'Attente de Messages",
        "c28_title": "Limitation de Débit",
        "c29_title": "Passerelles API",
        "c30_title": "Idempotence"
    },
    "pt": {
        "main_title": "Conceitos de Design de Sistemas",
        "main_subtitle": "30 Conceitos fundamentais visualizados e animados.",
        "nav_back": "Voltar ao Início",
        "nav_prev": "Anterior",
        "nav_next": "Próximo",
        "viz_placeholder": "Em Breve",
        "c01_title": "Arquitetura Cliente-Servidor",
        "c02_title": "Endereço IP",
        "c03_title": "DNS",
        "c04_title": "Proxy / Proxy Reverso",
        "c05_title": "Latência",
        "c06_title": "HTTP/HTTPS",
        "c07_title": "APIs",
        "c08_title": "API REST",
        "c09_title": "GraphQL",
        "c10_title": "Bancos de Dados",
        "c11_title": "SQL vs NoSQL",
        "c12_title": "Escalonamento Vertical",
        "c13_title": "Escalonamento Horizontal",
        "c14_title": "Balanceadores de Carga",
        "c15_title": "Indexação de Banco de Dados",
        "c16_title": "Replicação",
        "c17_title": "Sharding",
        "c18_title": "Particionamento Vertical",
        "c19_title": "Cache",
        "c20_title": "Desnormalização",
        "c21_title": "Teorema CAP",
        "c22_title": "Armazenamento de Blob",
        "c23_title": "CDN",
        "c24_title": "WebSockets",
        "c25_title": "Webhooks",
        "c26_title": "Microsserviços",
        "c27_title": "Filas de Mensagens",
        "c28_title": "Rate Limiting",
        "c29_title": "Gateways de API",
        "c30_title": "Idempotência"
    }
};
window.translations = translations;